name: Deploy to Render

on:
  push:
    tags:
      - '*'  # Se ejecuta solo cuando se crea un tag
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test  # Solo se ejecuta si el trabajo 'test' tuvo éxito
    if: success()  # Además, verifica que las pruebas hayan pasado
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Verify Pull Request Merge
        run: |
          echo "Skipping check because deploys are triggered only on tags"
        # Nota: como estamos usando 'push' con tags, ya sabemos que es código mergeado

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
