name: Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]  # Esto asegura que solo se ejecute en PR cerrados (mergeados)

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q  # Modifica según tus necesidades de pruebas

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test  # Esto asegura que el despliegue solo se ejecute si el trabajo 'test' ha tenido éxito
    if: github.event.pull_request.merged == true && success()  # Verifica si el PR fue mergeado y si las pruebas fueron exitosas
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
